# Nama alur kerja (workflow) Anda
name: Run Preprocessing Pipeline

# Pemicu (trigger) kapan workflow ini akan berjalan
on:
  # Jalankan setiap kali ada 'push' ke branch 'main'
  push:
    branches: [ main ]
  # Juga bisa dijalankan manual dari tab Actions di GitHub
  workflow_dispatch:

# Daftar pekerjaan (jobs) yang akan dilakukan
jobs:
  build:
    # Menentukan jenis server/runner yang akan digunakan
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dieksekusi secara berurutan
    steps:
      # 1. Mengunduh kode dari repository Anda ke server
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Menyiapkan lingkungan Python versi 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Menginstall semua library yang dibutuhkan dari requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Menjalankan skrip preprocessing
      - name: Run Preprocessing Script
        run: python preprocessing/automate_preprocessing.py

      # 5. Mengunggah hasil preprocessing sebagai "artifact"
      - name: Upload Processed Data Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: preprocessing/data_processed/dataset_rs_processed.csv